filebeat.inputs:
  - type: filestream
    id: app-json-log
    paths:
      - /logs/app.json.log
    parsers:
      - ndjson:
          target: ""
          overwrite_keys: true
          add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "app-logs-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.name: "app-logs"
setup.template.pattern: "app-logs-*"
